import type { Medicine, Manufacturer } from '@/types';

export const medicines: Medicine[] = [
  {
    id: '1',
    name: 'Paracetamol 500mg',
    manufacturer: 'Pharma Inc.',
    form: 'Tablet',
    therapeuticCategory: 'Analgesic',
    imageUrl: 'https://placehold.co/400x300.png',
    price: 5.99,
    inStock: true,
  },
  {
    id: '2',
    name: 'Amoxicillin 250mg',
    manufacturer: 'MediHealth',
    form: 'Capsule',
    therapeuticCategory: 'Antibiotic',
    imageUrl: 'https://placehold.co/400x300.png',
    price: 12.5,
    inStock: false,
  },
  {
    id: '3',
    name: 'Ibuprofen Syrup',
    manufacturer: 'HealthWell',
    form: 'Syrup',
    therapeuticCategory: 'Analgesic',
    imageUrl: 'https://placehold.co/400x300.png',
    price: 8.75,
    inStock: true,
  },
  {
    id: '4',
    name: 'Atorvastatin 20mg',
    manufacturer: 'Pharma Inc.',
    form: 'Tablet',
    therapeuticCategory: 'Cardiovascular',
    imageUrl: 'https://placehold.co/400x300.png',
    price: 25.0,
    inStock: true,
  },
  {
    id: '5',
    name: 'Salbutamol Inhaler',
    manufacturer: 'BreatheEasy',
    form: 'Liquid',
    therapeuticCategory: 'Respiratory',
    imageUrl: 'https://placehold.co/400x300.png',
    price: 18.2,
    inStock: false,
  },
  {
    id: '6',
    name: 'Omeprazole 20mg',
    manufacturer: 'MediHealth',
    form: 'Capsule',
    therapeuticCategory: 'Gastrointestinal',
    imageUrl: 'https://placehold.co/400x300.png',
    price: 15.99,
    inStock: true,
  },
  {
    id: '7',
    name: 'Acyclovir Cream',
    manufacturer: 'HealthWell',
    form: 'Ointment',
    therapeuticCategory: 'Antiviral',
    imageUrl: 'https://placehold.co/400x300.png',
    price: 22.0,
    inStock: true,
  },
  {
    id: '8',
    name: 'Ciprofloxacin Eye Drops',
    manufacturer: 'BreatheEasy',
    form: 'Liquid',
    therapeuticCategory: 'Antibiotic',
    imageUrl: 'https://placehold.co/400x300.png',
    price: 13.45,
    inStock: true,
  },
];

export const manufacturers: Manufacturer[] = [
    { id: '1', name: 'Pharma Inc.', location: 'New York, USA', logoUrl: 'https://placehold.co/100x100.png' },
    { id: '2', name: 'MediHealth', location: 'London, UK', logoUrl: 'https://placehold.co/100x100.png' },
    { id: '3', name: 'HealthWell', location: 'Paris, France', logoUrl: 'https://placehold.co/100x100.png' },
    { id: '4', name: 'BreatheEasy', location: 'Tokyo, Japan', logoUrl: 'https://placehold.co/100x100.png' },
];
