import type { Medicine } from '@/types';

export const medicines: Medicine[] = [
  {
    id: '1',
    name: 'Paracetamol 500mg',
    manufacturer: 'Pharma Inc.',
    form: 'Tablet',
    therapeuticCategory: 'Analgesic',
    imageUrl: 'https://placehold.co/400x300.png',
    price: 5.99,
  },
  {
    id: '2',
    name: 'Amoxicillin 250mg',
    manufacturer: 'MediHealth',
    form: 'Capsule',
    therapeuticCategory: 'Antibiotic',
    imageUrl: 'https://placehold.co/400x300.png',
    price: 12.5,
  },
  {
    id: '3',
    name: 'Ibuprofen Syrup',
    manufacturer: 'HealthWell',
    form: 'Syrup',
    therapeuticCategory: 'Analgesic',
    imageUrl: 'https://placehold.co/400x300.png',
    price: 8.75,
  },
  {
    id: '4',
    name: 'Atorvastatin 20mg',
    manufacturer: 'Pharma Inc.',
    form: 'Tablet',
    therapeuticCategory: 'Cardiovascular',
    imageUrl: 'https://placehold.co/400x300.png',
    price: 25.0,
  },
  {
    id: '5',
    name: 'Salbutamol Inhaler',
    manufacturer: 'BreatheEasy',
    form: 'Liquid',
    therapeuticCategory: 'Respiratory',
    imageUrl: 'https://placehold.co/400x300.png',
    price: 18.2,
  },
  {
    id: '6',
    name: 'Omeprazole 20mg',
    manufacturer: 'MediHealth',
    form: 'Capsule',
    therapeuticCategory: 'Gastrointestinal',
    imageUrl: 'https://placehold.co/400x300.png',
    price: 15.99,
  },
  {
    id: '7',
    name: 'Acyclovir Cream',
    manufacturer: 'HealthWell',
    form: 'Ointment',
    therapeuticCategory: 'Antiviral',
    imageUrl: 'https://placehold.co/400x300.png',
    price: 22.0,
  },
  {
    id: '8',
    name: 'Ciprofloxacin Eye Drops',
    manufacturer: 'BreatheEasy',
    form: 'Liquid',
    therapeuticCategory: 'Antibiotic',
    imageUrl: 'https://placehold.co/400x300.png',
    price: 13.45,
  },
];
